# Generated by Django 3.2.18 on 2023-04-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='bike_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='bike_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_for',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Parts', 'Parts')], default='Bike', max_length=100),
            preserve_default=False,
        ),
    ]
