# Generated by Django 3.2.18 on 2023-04-22 20:58

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_auto_20230423_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bike',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[768, 768], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_photo_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[768, 768], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_photo_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[768, 768], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_photo_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[768, 768], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_photo_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[768, 768], upload_to='photos/%Y/%m/%d/'),
        ),
    ]
