# Generated by Django 3.2.18 on 2023-04-24 20:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0004_auto_20230424_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='rent_price',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BikeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('price', models.IntegerField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bike.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bike Order',
                'verbose_name_plural': 'Bikes Orders',
            },
        ),
    ]
