# Generated by Django 3.2.18 on 2023-04-22 18:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bike', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField(default=datetime.date.today, validators=[rent.models.Rent.Date_validation])),
                ('dropoff_date', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(choices=[('New Baneshwor', 'New Baneshwor'), ('Chabahel', 'Chabahel'), ('Kalanki', 'Kalanki'), ('Koteshwor', 'Koteshwor'), ('Gongabu', 'Gongabu'), ('Tripureshwor', 'Tripureshwor'), ('Baluwatar', 'Baluwatar'), ('Kamaladi', 'Kamaladi')], max_length=100)),
                ('rented_date', models.DateTimeField(auto_now_add=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_bike', to='bike.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rent',
                'verbose_name_plural': 'Rents',
            },
        ),
    ]
