# Generated by Django 3.2.18 on 2023-04-22 18:31

from django.db import migrations, models
import rent.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='dropoff_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='pickup_date',
            field=models.DateField(validators=[rent.models.Rent.Date_validation]),
        ),
    ]
