# Generated by Django 3.2.18 on 2023-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20230424_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
