# Generated by Django 3.2.18 on 2023-04-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
