# Generated by Django 3.2.18 on 2023-04-24 17:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='parts_photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1080, 768], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='parts_photo_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1080, 768], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='parts_photo_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1080, 768], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='parts_photo_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1080, 768], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='parts_photo_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1080, 768], upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='SparepartsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='spareparts.spareparts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spareparts Review',
                'verbose_name_plural': 'Spareparts Reviews',
            },
        ),
    ]
