# Generated by Django 3.2.18 on 2023-04-24 18:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spareparts', '0002_auto_20230424_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparepartsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('price', models.IntegerField()),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='spareparts.spareparts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spareparts Order',
                'verbose_name_plural': 'Spareparts Orders',
            },
        ),
    ]
